# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/Container/MulleObjCContainerDescription.m
src/Container/MulleObjCContainerIntegerCallback.m
src/Container/MulleObjCContainerPointerCallback.m
src/Container/MulleObjCContainerSELCallback.m
src/Container/NSArray/NSArray+NSSortDescriptor.m
src/Container/NSArray/NSArray+NSString.m
src/Container/NSDictionary/NSDictionary+NSString.m
src/Container/NSDictionary/NSMapTable+NSArray+NSString.m
src/Container/NSSet/NSHashTable+NSArray+NSString.m
src/Container/NSSet/NSSet+NSString.m
src/Container/NSSortDescriptor+NSCoder.m
src/Container/NSSortDescriptor.m
src/Date/_MulleObjCConcreteCalendarDate.m
src/Date/NSCalendarDate+NSDateFormatter.m
src/Date/NSCalendarDate.m
src/Date/NSDateFormatter.m
src/Date/NSDate+NSCalendarDate.m
src/Date/NSDate+NSDateFormatter.m
src/Exception/NSAssertionHandler.m
src/Exception/NSError+String.m
src/Exception/NSError.m
src/Exception/NSException+String.m
src/Exception/NSException.m
src/Locale/NSArray+NSLocale.m
src/Locale/NSDictionary+NSLocale.m
src/Locale/NSLocale.m
src/Locale/NSNumberFormatter.m
src/Locale/NSNumber+NSLocale.m
src/Locale/NSScanner+NSLocale.m
src/Locale/NSString+NSLocale.m
src/Notification/NSNotificationCenter.m
src/Notification/NSNotification.m
src/Notification/NSThread+NSNotification.m
src/TimeZone/_MulleGMTTimeZone.m
src/TimeZone/NSTimeZone.m
src/Undo/NSUndoManager.m
src/Value/MulleObjCCharacterBitmap.m
src/Value/_MulleObjCCheatingASCIICharacterSet.m
src/Value/_MulleObjCConcreteBitmapCharacterSet.m
src/Value/_MulleObjCConcreteCharacterSet.m
src/Value/_MulleObjCConcreteInvertedCharacterSet.m
src/Value/_MulleObjCConcreteRangeCharacterSet.m
src/Value/NSArray+StringComponents.m
src/Value/NSCharacterSet.m
src/Value/NSData+Components.m
src/Value/NSFormatter.m
src/Value/NSMutableCharacterSet.m
src/Value/NSMutableString+Search.m
src/Value/NSScanner.m
src/Value/NSString+Components.m
src/Value/NSString+DoubleQuotes.m
src/Value/NSString+Escaping.m
src/Value/NSString+NSCharacterSet.m
src/Value/NSString+Search.m
src/mulle-foundation-universeconfiguration.m
)

#
# contents selected with patternfile ??-source--stage2-sources
#
set( STAGE2_SOURCES
src/MulleObjCLoader+MulleObjCStandardFoundation.m
)

#
# contents selected with patternfile ??-source--standalone-sources
#
set( STANDALONE_SOURCES
src/mulle-foundation-standalone.m
)
