/*
 *   This file will be regenerated by `mulle-sde reflect` and any edits will be
 *   lost. Suppress generation of this file with:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not generate any header files:
 *      mulle-sde environment --global \
 *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
 */

#ifndef _MulleObjCStandardFoundation_import_h__
#define _MulleObjCStandardFoundation_import_h__

// How to tweak the following MulleObjCValueFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCValueFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCValueFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCValueFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCValueFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCValueFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCValueFoundation no-os-<osname>`
# import <MulleObjCValueFoundation/MulleObjCValueFoundation.h>   // MulleObjCValueFoundation

// How to tweak the following MulleObjCContainerFoundation #import
//    remove:             `mulle-sourcetree mark MulleObjCContainerFoundation no-header`
//    rename:             `mulle-sde dependency|library set MulleObjCContainerFoundation include whatever.h`
//    toggle #import:     `mulle-sourcetree mark MulleObjCContainerFoundation [no-]import`
//    toggle public:      `mulle-sourcetree mark MulleObjCContainerFoundation [no-]public`
//    toggle optional:    `mulle-sourcetree mark MulleObjCContainerFoundation [no-]require`
//    remove for os:      `mulle-sourcetree mark MulleObjCContainerFoundation no-os-<osname>`
# import <MulleObjCContainerFoundation/MulleObjCContainerFoundation.h>   // MulleObjCContainerFoundation

#ifdef __has_include
# if __has_include( "_MulleObjCStandardFoundation-include.h")
#  include "_MulleObjCStandardFoundation-include.h"
# endif
#endif


#endif
