/*
 *   This file will be regenerated by `mulle-sourcetree-to-c` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

#ifndef _mulle_objc_standard_foundation_include_h__
#define _mulle_objc_standard_foundation_include_h__

// You can tweak the following #include with these commands.
// (Use BA519C41-BB27-4DA5-AF0D-40CFDB888C8E instead of mulle-unicode if there are duplicate entries)
//    remove #include:: `mulle-sde dependency mark mulle-unicode no-header`
//    rename:              `mulle-sde dependency|library set mulle-unicode include whatever.h`
//    reorder:             `mulle-sde dependency move mulle-unicode <up|down>`
//    toggle #include:    `mulle-sde dependency mark mulle-unicode [no-]import`
//    toggle public:       `mulle-sde dependency mark mulle-unicode [no-]public`
//    toggle optional:     `mulle-sde dependency mark mulle-unicode [no-]require`
//    remove for platform: `mulle-sde dependency mark mulle-unicode no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#include <mulle-unicode/mulle-unicode.h>   // mulle-unicode

#endif
