      { @selector( MulleObjCLoader), @selector( MulleObjCContainerFoundation) },      // 47a9beb6;MulleObjCLoader;2132102f;MulleObjCContainerFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCTimeFoundation) },      // 47a9beb6;MulleObjCLoader;cc20d48b;MulleObjCTimeFoundation
      { @selector( MulleObjCLoader), @selector( MulleObjCValueFoundation) },      // 47a9beb6;MulleObjCLoader;535d5103;MulleObjCValueFoundation
      { @selector( NSArray), @selector( DataComponents) },      // 233490fe;NSArray;486bf892;DataComponents
      { @selector( NSArray), @selector( NSLocale) },      // 233490fe;NSArray;22b7d78c;NSLocale
      { @selector( NSArray), @selector( NSSortDescriptor) },      // 233490fe;NSArray;38a79ab2;NSSortDescriptor
      { @selector( NSArray), @selector( NSString) },      // 233490fe;NSArray;1994a171;NSString
      { @selector( NSArray), @selector( StringComponents) },      // 233490fe;NSArray;6e3b19c0;StringComponents
      { @selector( NSAssertionHandler), MULLE_OBJC_NO_CATEGORYID },      // a1951b2b;NSAssertionHandler;;
      { @selector( NSCalendarDate), @selector( NSDateFormatter) },      // b8742fcb;NSCalendarDate;6d2cd542;NSDateFormatter
      { @selector( NSCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // b8742fcb;NSCalendarDate;;
      { @selector( NSCharacterSet), @selector( MutableCopy) },      // bb258d72;NSCharacterSet;78d7050b;MutableCopy
      { @selector( NSCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // bb258d72;NSCharacterSet;;
      { @selector( NSData), @selector( Components) },      // 8fce7861;NSData;c6c03895;Components
      { @selector( NSDate), @selector( NSCalendarDate) },      // cfcedd21;NSDate;b8742fcb;NSCalendarDate
      { @selector( NSDate), @selector( NSDateFormatter) },      // cfcedd21;NSDate;6d2cd542;NSDateFormatter
      { @selector( NSDateFormatter), MULLE_OBJC_NO_CATEGORYID },      // 6d2cd542;NSDateFormatter;;
      { @selector( NSDictionary), @selector( NSLocale) },      // 8b2abcad;NSDictionary;22b7d78c;NSLocale
      { @selector( NSDictionary), @selector( NSString) },      // 8b2abcad;NSDictionary;1994a171;NSString
      { @selector( NSError), @selector( String) },      // 17836f0e;NSError;04f48586;String
      { @selector( NSError), MULLE_OBJC_NO_CATEGORYID },      // 17836f0e;NSError;;
      { @selector( NSException), @selector( String) },      // 332ec6f9;NSException;04f48586;String
      { @selector( NSException), MULLE_OBJC_NO_CATEGORYID },      // 332ec6f9;NSException;;
      { @selector( NSFormatter), MULLE_OBJC_NO_CATEGORYID },      // d5e6770e;NSFormatter;;
      { @selector( NSLocale), MULLE_OBJC_NO_CATEGORYID },      // 22b7d78c;NSLocale;;
      { @selector( NSMutableArray), @selector( NSSortDescriptor) },      // f5e6dbdd;NSMutableArray;38a79ab2;NSSortDescriptor
      { @selector( NSMutableCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // a5cef654;NSMutableCharacterSet;;
      { @selector( NSMutableString), @selector( Search) },      // 63662493;NSMutableString;646a2c9c;Search
      { @selector( NSNotification), MULLE_OBJC_NO_CATEGORYID },      // 4cf6fadb;NSNotification;;
      { @selector( NSNotificationCenter), MULLE_OBJC_NO_CATEGORYID },      // 1c4865c0;NSNotificationCenter;;
      { @selector( NSNumber), @selector( NSLocale) },      // 8ba34f39;NSNumber;22b7d78c;NSLocale
      { @selector( NSNumberFormatter), MULLE_OBJC_NO_CATEGORYID },      // 60a672fc;NSNumberFormatter;;
      { @selector( NSObject), @selector( MulleCompareDescription) },      // b3a66256;NSObject;9df35a1c;MulleCompareDescription
      { @selector( NSObject), @selector( _NSCalendarDate) },      // b3a66256;NSObject;83e2187c;_NSCalendarDate
      { @selector( NSObject), @selector( _NSLocale) },      // b3a66256;NSObject;973379b2;_NSLocale
      { @selector( NSObject), @selector( _NSTimeZone) },      // b3a66256;NSObject;f3165c68;_NSTimeZone
      { @selector( NSScanner), @selector( NSLocale) },      // 0b3d6aca;NSScanner;22b7d78c;NSLocale
      { @selector( NSScanner), MULLE_OBJC_NO_CATEGORYID },      // 0b3d6aca;NSScanner;;
      { @selector( NSSet), @selector( NSString) },      // 9f69e3e4;NSSet;1994a171;NSString
      { @selector( NSSortDescriptor), @selector( NSCoder) },      // 38a79ab2;NSSortDescriptor;100c54ba;NSCoder
      { @selector( NSSortDescriptor), MULLE_OBJC_NO_CATEGORYID },      // 38a79ab2;NSSortDescriptor;;
      { @selector( NSString), @selector( Components) },      // 1994a171;NSString;c6c03895;Components
      { @selector( NSString), @selector( Escaping) },      // 1994a171;NSString;742c5512;Escaping
      { @selector( NSString), @selector( Locale) },      // 1994a171;NSString;d6e5bb7d;Locale
      { @selector( NSString), @selector( NSCharacterSet) },      // 1994a171;NSString;bb258d72;NSCharacterSet
      { @selector( NSString), @selector( Search) },      // 1994a171;NSString;646a2c9c;Search
      { @selector( NSThread), @selector( NSNotification) },      // c81b9c22;NSThread;4cf6fadb;NSNotification
      { @selector( NSTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 190d1ade;NSTimeZone;;
      { @selector( NSUndoManager), MULLE_OBJC_NO_CATEGORYID },      // 0e5330bc;NSUndoManager;;
      { @selector( _MulleGMTTimeZone), MULLE_OBJC_NO_CATEGORYID },      // d6f534a3;_MulleGMTTimeZone;;
      { @selector( _MulleObjCASCIIString), @selector( Components) },      // b82142dd;_MulleObjCASCIIString;c6c03895;Components
      { @selector( _MulleObjCConcreteBitmapCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 0846adc2;_MulleObjCConcreteBitmapCharacterSet;;
      { @selector( _MulleObjCConcreteCalendarDate), MULLE_OBJC_NO_CATEGORYID },      // a2be208e;_MulleObjCConcreteCalendarDate;;
      { @selector( _MulleObjCConcreteCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // ba1004b2;_MulleObjCConcreteCharacterSet;;
      { @selector( _MulleObjCConcreteInvertedCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 91ba9925;_MulleObjCConcreteInvertedCharacterSet;;
      { @selector( _MulleObjCConcreteRangeCharacterSet), MULLE_OBJC_NO_CATEGORYID },      // 09c86c6e;_MulleObjCConcreteRangeCharacterSet;;
      { @selector( _MulleObjCLocalTimeZone), MULLE_OBJC_NO_CATEGORYID },      // 5813d6fc;_MulleObjCLocalTimeZone;;
      { @selector( _MulleObjCTaggedPointerChar5String), @selector( Components) },      // 2a6d1009;_MulleObjCTaggedPointerChar5String;c6c03895;Components
      { @selector( _MulleObjCTaggedPointerChar7String), @selector( Components) },      // d68ecb24;_MulleObjCTaggedPointerChar7String;c6c03895;Components
      { @selector( _MulleObjCUTF16String), @selector( Components) },      // d817650f;_MulleObjCUTF16String;c6c03895;Components
      { @selector( _MulleObjCUTF16String), @selector( Search) },      // d817650f;_MulleObjCUTF16String;646a2c9c;Search
      { @selector( _MulleObjCUTF32String), @selector( Components) },      // 318d8f60;_MulleObjCUTF32String;c6c03895;Components
