/*
   This file will be regenerated by `mulle-sde update|monitor`.
   Edits will be lost. Suppress this file with:

   mulle-sde environment set MULLE_SOURCETREE_TO_C_INCLUDE_FILE DISABLE
*/

#ifndef _mulle_objc_standard_foundation_include_h__
#define _mulle_objc_standard_foundation_include_h__

# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

# include <mulle-utf/mulle-utf.h>   // mulle-utf

# include <mulle-sprintf/mulle-sprintf.h>   // mulle-sprintf

#endif
