/*
* This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SOURCETREE_TO_C_IMPORT_FILE NONE|DISABLE.
*/

#ifndef _mulle_objc_standard_foundation_import_h__
#define _mulle_objc_standard_foundation_import_h__

# import <MulleObjC/MulleObjC.h>   // MulleObjC

#endif
