/*
*   This file will be regenerated by `mulle-sde update|monitor`.
* Edits will be lost.
* Suppress this file with MULLE_SDE_INCLUDE_FILENAME NONE|DISABLE.
*/

#ifndef _mulle_objc_standard_foundation_include_h__
#define _mulle_objc_standard_foundation_include_h__

# include <mulle-buffer/mulle-buffer.h>   // mulle-buffer

# include <mulle-utf/mulle-utf.h>   // mulle-utf

# include <mulle-sprintf/mulle-sprintf.h>   // mulle-sprintf

#endif
