/*
*   This file will be regenerated by `mulle-sde update` and any edits will be
*   lost. Suppress generation of this file with:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
*
*   To not generate any header files:
*      mulle-sde environment --global *         set MULLE_SOURCETREE_TO_C_RUN DISABLE
*/

#ifndef _mulle_objc_standard_foundation_import_h__
#define _mulle_objc_standard_foundation_import_h__

// remove with `mulle-sourcetree mark MulleObjC no-header`
// rename with `mulle-sourcetree mark MulleObjC set include whatever.h`
# import <MulleObjC/MulleObjC.h>   // MulleObjC

#include "_MulleObjCStandardFoundation-include.h"


#endif
