//
//  MulleObjCLoader+Foundation.m
//  MulleObjCFoundation
//
//  Created by Nat! on 11.05.17.
//  Copyright © 2017 Mulle kybernetiK. All rights reserved.
//

#import "MulleObjCLoader+Foundation.h"


@implementation MulleObjCLoader( Foundation)

+ (struct _mulle_objc_dependency *) dependencies
{
   /* dependencies.inc are generated by:

    ```
    mulle-build
    mulle-objc-list -d build/libMulleObjCFoundationStandalone.dylib | fgrep -w -v 'MulleObjCLoader' |  sort > src/dependencies.inc
    ```

    */

   static struct _mulle_objc_dependency   dependencies[] =
   {
      // dependency on MulleObjCLoader is implicit due to
      // inheritance
#include "dependencies.inc"
      { MULLE_OBJC_NO_CLASSID, MULLE_OBJC_NO_CATEGORYID }
   };

   return( dependencies);
}

@end
